import type { Metadata } from 'next';
import { Breadcrumbs, JsonLd, breadcrumbJsonLd, canonical } from '@/lib/seo';

/**
 * Privacy policy.
 *
 * IMPORTANT: this describes accurately what the software currently does, which
 * is the hard part and the part only the engineers know. It is NOT legal advice
 * and has not been reviewed by a solicitor. Before taking payment or launching
 * publicly it must be reviewed against UK GDPR / EU GDPR and, if selling to
 * California, CCPA — particularly the lawful-basis wording and the controller
 * details, which are placeholders below.
 *
 * Keep this page truthful as the software changes. A privacy policy that
 * describes an older version of the product is worse than none.
 */

export const metadata: Metadata = {
  title: 'Privacy',
  description:
    'What personal data Astrolapp collects, why, where it is stored, and how to remove it.',
  alternates: { canonical: canonical('/privacy') },
};

const LAST_UPDATED = '14 August 2026';

export default function PrivacyPage() {
  const crumbs = [
    { name: 'Home', path: '/' },
    { name: 'Privacy', path: '/privacy' },
  ];

  return (
    <article className="max-w-2xl">
      <JsonLd json={breadcrumbJsonLd(crumbs)} />
      <Breadcrumbs crumbs={crumbs} />

      <h1 className="font-serif text-3xl">Privacy</h1>
      <p className="mt-2 text-xs text-parchment-faint">Last updated {LAST_UPDATED}</p>

      <div className="mt-8 space-y-8 text-sm leading-relaxed text-parchment-muted">
        <section>
          <h2 className="font-serif text-xl text-parchment">The short version</h2>
          <p className="mt-3">
            To calculate a chart we need your birth date, and ideally your birth time and place.
            That is personal data and we treat it as such. We do not sell it, we do not use it for
            advertising, and you can delete it at any time. Your birth details are never placed in a
            web address, so they cannot leak through browser history, referrer headers or server
            access logs.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl text-parchment">What we collect</h2>
          <dl className="mt-3 space-y-4">
            <div>
              <dt className="font-medium text-parchment">Birth details</dt>
              <dd className="mt-1">
                Date, and optionally time, time zone, coordinates and a place name. Used solely to
                compute your chart. Without a birth time we cannot calculate houses, and we say so
                rather than guessing.
              </dd>
            </div>
            <div>
              <dt className="font-medium text-parchment">Your name</dt>
              <dd className="mt-1">
                Optional, and used only for numerology. Leave it blank and the numerology sections
                are simply omitted.
              </dd>
            </div>
            <div>
              <dt className="font-medium text-parchment">Computed results</dt>
              <dd className="mt-1">
                Charts and readings derived from the above. These are caches — deleting your profile
                removes them too, automatically.
              </dd>
            </div>
          </dl>
        </section>

        <section>
          <h2 className="font-serif text-xl text-parchment">Where it is stored</h2>
          <p className="mt-3">
            At present the application stores your birth profile in an HTTP-only cookie in your own
            browser, not on our servers. It is marked{' '}
            <code className="text-parchment">HttpOnly</code> and{' '}
            <code className="text-parchment">SameSite=Lax</code>, so it is not readable by scripts
            on the page. Clearing it, or using the delete button on the profile page, removes it
            completely.
          </p>
          <p className="mt-3">
            When accounts are introduced, birth data will move to a database with row-level security
            so that one account cannot read another&rsquo;s records. This page will be updated
            before that change ships, not after.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl text-parchment">Artificial intelligence</h2>
          <p className="mt-3">
            Readings are generated by our own calculation engines, not by a language model. Where an
            AI model is used to improve the wording, it receives only the already-computed facts and
            interpretations — never your birth date, birth time, coordinates or name. Numerology is
            sent as the resulting number alone, without the arithmetic, because that arithmetic
            would reveal your date of birth.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl text-parchment">What we do not do</h2>
          <ul className="mt-3 list-disc space-y-1.5 pl-5">
            <li>We do not sell or rent personal data.</li>
            <li>
              We do not use birth data for advertising or profiling beyond producing your reading.
            </li>
            <li>We do not put birth details in URLs, where they would end up in logs.</li>
            <li>
              We do not record birth dates, times, coordinates or names in analytics or error
              reports.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="font-serif text-xl text-parchment">Your rights</h2>
          <p className="mt-3">
            Under UK and EU data protection law you may request access to your data, correction,
            deletion, or a copy in a portable format, and you may object to certain processing. The
            delete button on the profile page removes everything we hold immediately. For anything
            else, contact us at the address below.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl text-parchment">Contact</h2>
          <p className="mt-3">
            {/* Replace before launch. A privacy policy without a reachable controller is not compliant. */}
            Data controller and contact address to be confirmed before public launch.
          </p>
        </section>
      </div>
    </article>
  );
}
