/**
 * SEO helpers.
 *
 * Public pages exist to be found, but the brief is explicit that they must not
 * be thin. Every indexable page here carries genuinely unique, recomputed
 * astronomical data — not twelve rewrites of the same paragraph — and states
 * plainly which parts are calculated and which are traditional interpretation.
 *
 * Structured data is only emitted where it is actually valid for the page type.
 * Marking up a horoscope as, say, a FAQ to win a rich result would be misuse.
 */

/**
 * Canonical origin.
 *
 * This MUST be set in production. Falling back silently would emit
 * `http://localhost:3000` into every canonical tag, Open Graph URL and sitemap
 * entry — telling search engines the real site is a machine they cannot reach.
 * That is a quiet, total SEO failure, so it fails the build instead.
 */
function resolveSiteUrl(): string {
  const configured = process.env['NEXT_PUBLIC_SITE_URL'];
  if (configured !== undefined && configured.length > 0) {
    return configured.replace(/\/$/, '');
  }

  // Vercel injects these on real deployments, so a correct value is available
  // even when the variable was forgotten.
  const vercelHost = process.env['VERCEL_PROJECT_PRODUCTION_URL'] ?? process.env['VERCEL_URL'];
  if (vercelHost !== undefined && vercelHost.length > 0) {
    return `https://${vercelHost.replace(/\/$/, '')}`;
  }

  // Throwing here would make a plain local `next build` impossible, which is
  // worse than useless. Instead the fallback is obviously wrong, and
  // `pnpm release-check` fails on it before anything ships.
  return 'http://localhost:3000';
}

export const SITE_URL = resolveSiteUrl();

/**
 * True when the canonical host is still the local placeholder.
 *
 * A production deploy in this state emits `http://localhost:3000` into every
 * canonical tag, Open Graph URL and sitemap entry — telling search engines the
 * real site lives on a machine they cannot reach. Silent, and totally fatal to
 * the point of having public pages at all.
 */
export const SITE_URL_IS_PLACEHOLDER = SITE_URL.includes('localhost');

export const SITE_NAME = 'Astrolapp';

export function canonical(path: string): string {
  return `${SITE_URL}${path.startsWith('/') ? path : `/${path}`}`;
}

export interface Crumb {
  readonly name: string;
  readonly path: string;
}

/**
 * BreadcrumbList structured data.
 *
 * Valid on any page that genuinely sits in a hierarchy, which these do.
 */
export function breadcrumbJsonLd(crumbs: readonly Crumb[]): string {
  return JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: crumbs.map((crumb, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: crumb.name,
      item: canonical(crumb.path),
    })),
  });
}

/**
 * Article structured data for a dated, regenerated page.
 *
 * `dateModified` is the real computation instant, so the markup does not
 * overstate freshness.
 */
export function articleJsonLd(options: {
  headline: string;
  description: string;
  path: string;
  datePublished: string;
  dateModified: string;
}): string {
  return JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: options.headline,
    description: options.description,
    mainEntityOfPage: canonical(options.path),
    datePublished: options.datePublished,
    dateModified: options.dateModified,
    publisher: { '@type': 'Organization', name: SITE_NAME },
  });
}

/** Inline JSON-LD. Content is generated by us, never from user input. */
export function JsonLd({ json }: { json: string }) {
  return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: json }} />;
}

export function Breadcrumbs({ crumbs }: { crumbs: readonly Crumb[] }) {
  return (
    <nav aria-label="Breadcrumb" className="mb-6">
      <ol className="flex flex-wrap items-center gap-x-2 text-xs text-parchment-faint">
        {crumbs.map((crumb, index) => (
          <li key={crumb.path} className="flex items-center gap-x-2">
            {index > 0 && <span aria-hidden="true">/</span>}
            {index === crumbs.length - 1 ? (
              <span aria-current="page">{crumb.name}</span>
            ) : (
              <a
                href={crumb.path}
                className="underline-offset-4 hover:text-parchment hover:underline"
              >
                {crumb.name}
              </a>
            )}
          </li>
        ))}
      </ol>
    </nav>
  );
}
